ej.datavisualization.Diagram.Locale["pt-PT"] = {
cut: "Cortar",
copy: "Cópia",
paste: "Colar",
undo: "Desfazer",
redo: "Refazer",
selectAll: "Selecionar tudo",
grouping: "Agrupamento",
group: "Grupo",
ungroup: "Desagrupar",
order: "Ordem",
bringToFront: "Traga para frente",
moveForward: "Siga em frente",
sendBackward: "Recuar",
sendToBack: "Enviar para trás",
};
