ej.datavisualization.Diagram.Locale["it-IT"] = {
cut: "Tagliare",
copy: "Copia",
paste: "Incolla",
undo: "Disfare",
redo: "Rifare",
selectAll: "Seleziona tutto",
grouping: "Raggruppamento",
group: "Gruppo",
ungroup: "Separa",
order: "Ordine",
bringToFront: "Portare in primo piano",
moveForward: "spostare in avanti",
sendBackward: "Manda indietro",
sendToBack: "Mandare indietro",
};
