ej.datavisualization.Diagram.Locale["se-SE"] = {
cut: "Skära",
copy: "Kopiera",
paste: "Klistra",
undo: "Ångra",
redo: "Göra om",
selectAll: "Välj alla",
grouping: "gruppering",
group: "Grupp",
ungroup: "Dela upp",
order: "Beställa",
bringToFront: "Längst fram",
moveForward: "Gå framåt",
sendBackward: "Skicka bakåt",
sendToBack: "Skicka tillbaka",
};
