ej.datavisualization.Diagram.Locale["da-DK"] = {
cut: "Skære",
copy: "Kopi",
paste: "Indsæt",
undo: "Fortryd",
redo: "redo",
selectAll: "Vælg alle",
grouping: "Gruppering",
group: "Gruppe",
ungroup: "Opdel gruppe",
order: "Bestille",
bringToFront: "Placer forrest",
moveForward: "Komme videre",
sendBackward: "Flyt bagud",
sendToBack: "Bagest",
};
