ej.datavisualization.Diagram.Locale["ru-RU"] = {
cut: "Порез",
copy: "копия",
paste: "Вставить",
undo: "расстегивать",
redo: "переделывать",
selectAll: "Выбрать все",
grouping: "группирование",
group: "группа",
ungroup: "Ungroup",
order: "порядок",
bringToFront: "На передний план",
moveForward: "Двигаться вперед",
sendBackward: "Переместить назад",
sendToBack: "На задний план",
};
