ej.datavisualization.Diagram.Locale["pl-PL"] = {
cut: "Ciąć",
copy: "Kopiuj",
paste: "Pasta",
undo: "Cofnij",
redo: "Przerobić",
selectAll: "Zaznacz wszystko",
grouping: "Grupowanie",
group: "Grupa",
ungroup: "Ungroup",
order: "Zamówienie",
bringToFront: "Przesuń na wierzch",
moveForward: "Pójść naprzód",
sendBackward: "Wyślij do tyłu",
sendToBack: "Przesuń na spód",
};
